[package]
name = "sudoku"
version = "0.1.0"
authors = ["Tom BaÌˆrwinkel <dev@baerwinkel.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
